package com.br.second.tech.challenge.core.exception;

public class UsuarioNotFound extends RuntimeException {

    public UsuarioNotFound(String msg) {
        super(msg);
    }
}
